DATA_RAW = "data/raw/"
DATA_PROCESSED = "data/processed/"
MODEL_DIR = "models/"

SEGMENTS = [
    "PREAH_VIHEAR_TEMPLE",
    "TA_MUEN_THOM_TEMPLE",
    "TA_KRABEY_TEMPLE",
    "OSMACH_CHECKPOINT",
    "CHONG_CHOM_CHECKPOINT",
    "ARANYAPRATHET_POIPET",
    "PHANOM_DONG_RAK_RIDGE",
    "BAN_KRUAT",
    "KANTHARALAK",
    "SAMRAONG"
]

START_DATE = "2024-01-07"
END_DATE   = "2025-12-28"
FREQ = "W"
